from ... import ShopifyTroisTestCase

from shopify_trois import Shopify, Shop, Credentials, ShopifyException
from shopify_trois.engines.http.json import Json
from shopify_trois.engines.http.json_request import JsonRequest

class JsonEngineTestCase(ShopifyTroisTestCase):

    def test_class(self):
        expected = "json"
        self.assertEqual(Json.extension, expected)

        expected = "application/json; charset=utf-8"
        self.assertEqual(Json.mime, expected)

    def test_prepare_request(self):
        shop = Shop(name = 'test')
        credentials = Credentials()
        shopify = Shopify(shop = shop, credentials = credentials, engine=Json)

        request = JsonRequest()
        shopify.engine._prepare_request(request)
        expected = {
            "X-Shopify-Access-Token": None,
            "Content-Type": "application/json; charset=utf-8"
        }
        self.assertEquals(request.headers(), expected)

        request = JsonRequest()
        shopify.engine._prepare_request(request, use_access_token = False)
        expected = {
            "Content-Type": "application/json; charset=utf-8"
        }
        self.assertEquals(request.headers(), expected)

    def test_url_for_request(self):
        shop = Shop(name = 'test')
        credentials = Credentials()
        shopify = Shopify(shop = shop, credentials = credentials, engine=Json)

        request = JsonRequest()
        request.resource = "test"
        url = shopify.engine.url_for_request(request)
        # Note: the base request class does not have an extension.
        expected = "https://test.myshopify.com/admin/test.json"
        self.assertEquals(url, expected)

        request.resource = "test/mmmm food"
        url = shopify.engine.url_for_request(request)
        # Note: The url generated by url_for_request are not escaped. The
        # actual request.{method} will escape the url for us.
        expected = "https://test.myshopify.com/admin/test/mmmm food.json"
        self.assertEquals(url, expected)
